/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tanaka
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin_manage_requests
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Admin = new javax.swing.JTabbedPane();
        Manage_Timetables = new javax.swing.JPanel();
        LeftT = new javax.swing.JPanel();
        Separator = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Publish = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        RightT = new javax.swing.JPanel();
        Course = new javax.swing.JLabel();
        Module = new javax.swing.JLabel();
        Location = new javax.swing.JLabel();
        Start_Time = new javax.swing.JLabel();
        Duration = new javax.swing.JLabel();
        Staff_Allocation = new javax.swing.JLabel();
        Group = new javax.swing.JLabel();
        Course_Button = new javax.swing.JComboBox<>();
        Module_Button = new javax.swing.JComboBox<>();
        Location_Button = new javax.swing.JComboBox<>();
        StartTime_Button = new javax.swing.JComboBox<>();
        Duration_Button = new javax.swing.JComboBox<>();
        StaffAllocation_Button = new javax.swing.JComboBox<>();
        Group_Button = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();
        Manage_Requests = new javax.swing.JPanel();
        LeftR = new javax.swing.JPanel();
        Separator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        RightR = new javax.swing.JPanel();
        Add1 = new javax.swing.JButton();
        Add3 = new javax.swing.JButton();
        Display = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Edit = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LeftT.setPreferredSize(new java.awt.Dimension(650, 450));

        Separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course", "Module Name", "Module Code", "Room Location", "Time Slot", "Staff Allocation", "Group"
            }
        ));
        jScrollPane1.setViewportView(Table);

        Publish.setText("Publish");
        Publish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublishActionPerformed(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftTLayout = new javax.swing.GroupLayout(LeftT);
        LeftT.setLayout(LeftTLayout);
        LeftTLayout.setHorizontalGroup(
            LeftTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftTLayout.createSequentialGroup()
                .addGroup(LeftTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LeftTLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(LeftTLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Publish, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LeftTLayout.setVerticalGroup(
            LeftTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separator)
            .addGroup(LeftTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(LeftTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Publish)
                    .addComponent(Remove))
                .addContainerGap())
        );

        RightT.setPreferredSize(new java.awt.Dimension(650, 100));

        Course.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Course.setText("Course");

        Module.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Module.setText("Module");

        Location.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Location.setText("Location");

        Start_Time.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Start_Time.setText("Start Time");

        Duration.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Duration.setText("Duration");

        Staff_Allocation.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Staff_Allocation.setText("Staff Allocation");

        Group.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Group.setText("Group");

        Course_Button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Module_Button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Location_Button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        StartTime_Button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        StartTime_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTime_ButtonActionPerformed(evt);
            }
        });

        Duration_Button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        StaffAllocation_Button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Group_Button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightTLayout = new javax.swing.GroupLayout(RightT);
        RightT.setLayout(RightTLayout);
        RightTLayout.setHorizontalGroup(
            RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightTLayout.createSequentialGroup()
                .addGroup(RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Course)
                        .addGap(99, 99, 99)
                        .addComponent(Course_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Module)
                        .addGap(94, 94, 94)
                        .addComponent(Module_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Location)
                        .addGap(86, 86, 86)
                        .addComponent(Location_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Staff_Allocation)
                        .addGap(38, 38, 38)
                        .addComponent(StaffAllocation_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Group)
                        .addGap(106, 106, 106)
                        .addComponent(Group_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightTLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightTLayout.createSequentialGroup()
                                .addComponent(Start_Time)
                                .addGap(75, 75, 75)
                                .addComponent(StartTime_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightTLayout.createSequentialGroup()
                                .addComponent(Duration)
                                .addGap(86, 86, 86)
                                .addComponent(Duration_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46))
        );
        RightTLayout.setVerticalGroup(
            RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightTLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Course)
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Course_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Module)
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Module_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Location)
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Location_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Start_Time)
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(StartTime_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Duration)
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Duration_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Staff_Allocation)
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(StaffAllocation_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(RightTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Group)
                    .addGroup(RightTLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Group_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(Add))
        );

        javax.swing.GroupLayout Manage_TimetablesLayout = new javax.swing.GroupLayout(Manage_Timetables);
        Manage_Timetables.setLayout(Manage_TimetablesLayout);
        Manage_TimetablesLayout.setHorizontalGroup(
            Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_TimetablesLayout.createSequentialGroup()
                .addComponent(LeftT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightT, javax.swing.GroupLayout.PREFERRED_SIZE, 282, Short.MAX_VALUE))
        );
        Manage_TimetablesLayout.setVerticalGroup(
            Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftT, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addComponent(RightT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        Admin.addTab("Manage Timetables", Manage_Timetables);

        LeftR.setPreferredSize(new java.awt.Dimension(650, 450));

        Separator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Staff Name", "Time", "Date"
            }
        ));
        jScrollPane2.setViewportView(Table1);

        javax.swing.GroupLayout LeftRLayout = new javax.swing.GroupLayout(LeftR);
        LeftR.setLayout(LeftRLayout);
        LeftRLayout.setHorizontalGroup(
            LeftRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LeftRLayout.setVerticalGroup(
            LeftRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separator1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addGroup(LeftRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        RightR.setPreferredSize(new java.awt.Dimension(650, 100));

        Add1.setText("Accept");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });

        Add3.setText("Deny");
        Add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        Display.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        Edit.setViewportView(jTextArea2);

        javax.swing.GroupLayout RightRLayout = new javax.swing.GroupLayout(RightR);
        RightR.setLayout(RightRLayout);
        RightRLayout.setHorizontalGroup(
            RightRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightRLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(RightRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(Display)
                    .addGroup(RightRLayout.createSequentialGroup()
                        .addComponent(Add3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add1)))
                .addGap(25, 25, 25))
        );
        RightRLayout.setVerticalGroup(
            RightRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightRLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RightRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add1)
                    .addComponent(Add3))
                .addContainerGap())
        );

        javax.swing.GroupLayout Manage_RequestsLayout = new javax.swing.GroupLayout(Manage_Requests);
        Manage_Requests.setLayout(Manage_RequestsLayout);
        Manage_RequestsLayout.setHorizontalGroup(
            Manage_RequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_RequestsLayout.createSequentialGroup()
                .addComponent(LeftR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightR, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
        );
        Manage_RequestsLayout.setVerticalGroup(
            Manage_RequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftR, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addComponent(RightR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        Admin.addTab("Manage Requests", Manage_Requests);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 935, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       String Course = Course_Button.getSelectedItem().toString();
       String Module = Module_Button.getSelectedItem().toString();
       String Location = Location_Button.getSelectedItem().toString();     
       String StartTime = StartTime_Button.getSelectedItem().toString();
       String Duration = Duration_Button.getSelectedItem().toString();
       
       int TimeSlot1 = Integer.parseInt(StartTime)+Integer.parseInt(Duration);
       if(TimeSlot1>19){
       JOptionPane.showMessageDialog(Manage_Timetables, "Class cannot end after 7");
       }
       
       else{
       String TimeSlot = StartTime_Button.getSelectedItem() + ":00 - " + TimeSlot1 + ":00";
       String StaffAllocation = StaffAllocation_Button.getSelectedItem().toString();
       String Group = Group_Button.getSelectedItem().toString();
       
       Object[] row = {Course, Module, "Hello", Location, TimeSlot, StaffAllocation, Group};
       DefaultTableModel model = (DefaultTableModel) Table.getModel();
       model.addRow(row);  
       }
    }//GEN-LAST:event_AddActionPerformed

    private void PublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PublishActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
       DefaultTableModel model = (DefaultTableModel) Table.getModel();
       int Selection = Table.getSelectedRow();
       model.removeRow(Selection);
    }//GEN-LAST:event_RemoveActionPerformed

    private void StartTime_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTime_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartTime_ButtonActionPerformed

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add1ActionPerformed

    private void Add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add3;
    private javax.swing.JTabbedPane Admin;
    private javax.swing.JLabel Course;
    private javax.swing.JComboBox<String> Course_Button;
    private javax.swing.JScrollPane Display;
    private javax.swing.JLabel Duration;
    private javax.swing.JComboBox<String> Duration_Button;
    private javax.swing.JScrollPane Edit;
    private javax.swing.JLabel Group;
    private javax.swing.JComboBox<String> Group_Button;
    private javax.swing.JPanel LeftR;
    private javax.swing.JPanel LeftT;
    private javax.swing.JLabel Location;
    private javax.swing.JComboBox<String> Location_Button;
    private javax.swing.JPanel Manage_Requests;
    private javax.swing.JPanel Manage_Timetables;
    private javax.swing.JLabel Module;
    private javax.swing.JComboBox<String> Module_Button;
    private javax.swing.JButton Publish;
    private javax.swing.JButton Remove;
    private javax.swing.JPanel RightR;
    private javax.swing.JPanel RightT;
    private javax.swing.JSeparator Separator;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JComboBox<String> StaffAllocation_Button;
    private javax.swing.JLabel Staff_Allocation;
    private javax.swing.JComboBox<String> StartTime_Button;
    private javax.swing.JLabel Start_Time;
    private javax.swing.JTable Table;
    private javax.swing.JTable Table1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
