/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablingclient;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.*;
import org.netbeans.xml.schema.timetable.Event;

//import timetablewebservices.DatatypeConfigurationException_Exception;
/**
 *
 * @author Tanaka
 */
public class Admin extends javax.swing.JFrame {

    static adminRequestTableModel artm;
    static ManageTimetablesTableModel mttm;

    /**
     * Creates new form Admin_manage_requests
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin = new javax.swing.JTabbedPane();
        Manage_Requests = new javax.swing.JPanel();
        LeftR = new javax.swing.JPanel();
        Separator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        Course_Label_Manage_Requests = new javax.swing.JLabel();
        List<String> MRcourseIdsList = getCourseIds();

        String[] MRcourseIds = new String[MRcourseIdsList.size()];

        for (int i = 0; i < MRcourseIdsList.size(); i++){
            MRcourseIds[i] = MRcourseIdsList.get(i);
        }
        Course_Button2 = new javax.swing.JComboBox<>();
        RightR = new javax.swing.JPanel();
        Add1 = new javax.swing.JButton();
        Deny = new javax.swing.JButton();
        Request_Description_label = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();
        Manage_Timetables = new javax.swing.JPanel();
        Table_Panel = new javax.swing.JPanel();
        Separator = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventsTable = new javax.swing.JTable();
        Remove = new javax.swing.JButton();
        Dropdowns = new javax.swing.JTabbedPane();
        Rightt = new javax.swing.JPanel();
        Course = new javax.swing.JLabel();
        Module = new javax.swing.JLabel();
        Start_Time = new javax.swing.JLabel();
        Duration = new javax.swing.JLabel();
        Staff_Allocation = new javax.swing.JLabel();
        /*//List<String> locationNamesList = getLocationNames();

        String[] locationNames = new String[locationNamesList.size()];

        for (int i = 0; i < locationNamesList.size(); i++){
            locationNames[i] = locationNamesList.get(i);
            locationNames
        }*/
        Location_Button = new javax.swing.JComboBox<>();
        StartTime_Button = new javax.swing.JComboBox<>();
        Duration_Button = new javax.swing.JComboBox<>();
        StaffAllocation_Button = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();
        Group_Button = new javax.swing.JComboBox<>();
        Group = new javax.swing.JLabel();
        List<String> courseIdsList = getCourseIds();

        String[] courseIds = new String[courseIdsList.size()];

        for (int i = 0; i < courseIdsList.size(); i++){
            courseIds[i] = courseIdsList.get(i);
        }
        Course_Button = new javax.swing.JComboBox<>();
        Module_Button = new javax.swing.JComboBox<>();
        Location = new javax.swing.JLabel();
        Start_Time1 = new javax.swing.JLabel();
        Type_button = new javax.swing.JComboBox<>();
        Date = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        Rightt1 = new javax.swing.JPanel();
        Course1 = new javax.swing.JLabel();
        Module1 = new javax.swing.JLabel();
        Start_Time2 = new javax.swing.JLabel();
        Duration1 = new javax.swing.JLabel();
        Staff_Allocation1 = new javax.swing.JLabel();
        /*//List<String> locationNamesList = getLocationNames();

        String[] locationNames = new String[locationNamesList.size()];

        for (int i = 0; i < locationNamesList.size(); i++){
            locationNames[i] = locationNamesList.get(i);
            locationNames
        }*/
        Location_Button1 = new javax.swing.JComboBox<>();
        StartTime_Button1 = new javax.swing.JComboBox<>();
        Duration_Button1 = new javax.swing.JComboBox<>();
        StaffAllocation_Button1 = new javax.swing.JComboBox<>();
        Modify = new javax.swing.JButton();
        Group_Button1 = new javax.swing.JComboBox<>();
        Group1 = new javax.swing.JLabel();
        List<String> McourseIdsList = getCourseIds();

        String[] McourseIds = new String[McourseIdsList.size()];

        for (int i = 0; i < McourseIdsList.size(); i++){
            McourseIds[i] = McourseIdsList.get(i);
        }
        Course_Button1 = new javax.swing.JComboBox<>();
        Module_Button1 = new javax.swing.JComboBox<>();
        Location1 = new javax.swing.JLabel();
        Start_Time3 = new javax.swing.JLabel();
        Type_button1 = new javax.swing.JComboBox<>();
        Date1 = new javax.swing.JLabel();
        DateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Admin.setPreferredSize(new java.awt.Dimension(1000, 400));

        LeftR.setPreferredSize(new java.awt.Dimension(650, 450));

        Separator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        requestTable.setAutoCreateRowSorter(true);
        requestTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                requestTableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(requestTable);

        Course_Label_Manage_Requests.setText("Course:");

        Course_Button2.setModel(new javax.swing.DefaultComboBoxModel<String>(MRcourseIds));
        Course_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_Button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftRLayout = new javax.swing.GroupLayout(LeftR);
        LeftR.setLayout(LeftRLayout);
        LeftRLayout.setHorizontalGroup(
            LeftRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Course_Label_Manage_Requests)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Course_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LeftRLayout.setVerticalGroup(
            LeftRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Course_Label_Manage_Requests)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Course_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Separator1)
        );

        RightR.setPreferredSize(new java.awt.Dimension(650, 100));

        Add1.setText("Accept");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });

        Deny.setText("Deny");
        Deny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenyActionPerformed(evt);
            }
        });

        Request_Description_label.setText("Request Description");

        Display.setColumns(20);
        Display.setRows(5);
        ScrollPane.setViewportView(Display);

        javax.swing.GroupLayout RightRLayout = new javax.swing.GroupLayout(RightR);
        RightR.setLayout(RightRLayout);
        RightRLayout.setHorizontalGroup(
            RightRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightRLayout.createSequentialGroup()
                .addGroup(RightRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RightRLayout.createSequentialGroup()
                        .addComponent(Add1)
                        .addGap(180, 180, 180)
                        .addComponent(Deny))
                    .addGroup(RightRLayout.createSequentialGroup()
                        .addComponent(Request_Description_label)
                        .addGap(199, 199, 199)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RightRLayout.setVerticalGroup(
            RightRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Request_Description_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RightRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deny)
                    .addComponent(Add1))
                .addContainerGap())
        );

        javax.swing.GroupLayout Manage_RequestsLayout = new javax.swing.GroupLayout(Manage_Requests);
        Manage_Requests.setLayout(Manage_RequestsLayout);
        Manage_RequestsLayout.setHorizontalGroup(
            Manage_RequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_RequestsLayout.createSequentialGroup()
                .addComponent(LeftR, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RightR, javax.swing.GroupLayout.PREFERRED_SIZE, 339, Short.MAX_VALUE))
        );
        Manage_RequestsLayout.setVerticalGroup(
            Manage_RequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RightR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addComponent(LeftR, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        Admin.addTab("Manage Requests", Manage_Requests);

        Manage_Timetables.setPreferredSize(new java.awt.Dimension(940, 380));

        Table_Panel.setPreferredSize(new java.awt.Dimension(650, 450));

        Separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        eventsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(eventsTable);

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Table_PanelLayout = new javax.swing.GroupLayout(Table_Panel);
        Table_Panel.setLayout(Table_PanelLayout);
        Table_PanelLayout.setHorizontalGroup(
            Table_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Table_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Table_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Table_PanelLayout.createSequentialGroup()
                        .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 577, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Table_PanelLayout.setVerticalGroup(
            Table_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Table_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Remove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Separator)
        );

        Rightt.setPreferredSize(new java.awt.Dimension(650, 100));

        Course.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Course.setText("Course ID");

        Module.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Module.setText("Module");

        Start_Time.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Start_Time.setText("Start Time");

        Duration.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Duration.setText("Duration");

        Staff_Allocation.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Staff_Allocation.setText("Staff Allocation");

        Location_Button.setModel(new javax.swing.DefaultComboBoxModel<String>());

        StartTime_Button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        StartTime_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTime_ButtonActionPerformed(evt);
            }
        });

        Duration_Button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Group_Button.setModel(new javax.swing.DefaultComboBoxModel<String>());
        Group_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Group_ButtonActionPerformed(evt);
            }
        });

        Group.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Group.setText("Group");

        Course_Button.setModel(new javax.swing.DefaultComboBoxModel<String>(courseIds));
        Course_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_ButtonActionPerformed(evt);
            }
        });

        Module_Button.setModel(new javax.swing.DefaultComboBoxModel<String>());
        Module_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Module_ButtonActionPerformed(evt);
            }
        });

        Location.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Location.setText("Location");

        Start_Time1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Start_Time1.setText("Type");

        Type_button.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture", "Seminar", "Lab" }));
        Type_button.setToolTipText("");
        Type_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type_buttonActionPerformed(evt);
            }
        });

        Date.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Date.setText("Date");

        javax.swing.GroupLayout RighttLayout = new javax.swing.GroupLayout(Rightt);
        Rightt.setLayout(RighttLayout);
        RighttLayout.setHorizontalGroup(
            RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RighttLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RighttLayout.createSequentialGroup()
                        .addComponent(Start_Time)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RighttLayout.createSequentialGroup()
                        .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Location_Button, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Course_Button, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Module_Button, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RighttLayout.createSequentialGroup()
                                .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Course, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Module, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Staff_Allocation, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RighttLayout.createSequentialGroup()
                                        .addComponent(StartTime_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Duration)
                                            .addComponent(Duration_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Date, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(RighttLayout.createSequentialGroup()
                                .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(RighttLayout.createSequentialGroup()
                                        .addComponent(Location)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(RighttLayout.createSequentialGroup()
                                        .addComponent(Type_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Group_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16))
                            .addGroup(RighttLayout.createSequentialGroup()
                                .addComponent(Start_Time1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Group)
                                .addGap(74, 74, 74)))
                        .addGap(21, 21, 21))
                    .addGroup(RighttLayout.createSequentialGroup()
                        .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StaffAllocation_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        RighttLayout.setVerticalGroup(
            RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RighttLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Course)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Course_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Module)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Module_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Group)
                    .addComponent(Start_Time1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Group_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Location)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Location_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Date)
                .addGap(1, 1, 1)
                .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start_Time)
                    .addComponent(Duration))
                .addGap(10, 10, 10)
                .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartTime_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Duration_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Staff_Allocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RighttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffAllocation_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(369, 369, 369))
        );

        Dropdowns.addTab("Add", Rightt);

        Rightt1.setPreferredSize(new java.awt.Dimension(650, 100));

        Course1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Course1.setText("Course ID");

        Module1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Module1.setText("Module");

        Start_Time2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Start_Time2.setText("Start Time");

        Duration1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Duration1.setText("Duration");

        Staff_Allocation1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Staff_Allocation1.setText("Staff Allocation");

        Location_Button1.setModel(new javax.swing.DefaultComboBoxModel<String>());

        StartTime_Button1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        StartTime_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTime_Button1ActionPerformed(evt);
            }
        });

        Duration_Button1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        Modify.setText("Modify");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });

        Group_Button1.setModel(new javax.swing.DefaultComboBoxModel<String>());
        Group_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Group_Button1ActionPerformed(evt);
            }
        });

        Group1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Group1.setText("Group");

        Course_Button1.setModel(new javax.swing.DefaultComboBoxModel<String>(McourseIds));
        Course_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_Button1ActionPerformed(evt);
            }
        });

        Module_Button1.setModel(new javax.swing.DefaultComboBoxModel<String>());
        Module_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Module_Button1ActionPerformed(evt);
            }
        });

        Location1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Location1.setText("Location");

        Start_Time3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Start_Time3.setText("Type");

        Type_button1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture", "Seminar", "Lab" }));

        Date1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Date1.setText("Date");

        javax.swing.GroupLayout Rightt1Layout = new javax.swing.GroupLayout(Rightt1);
        Rightt1.setLayout(Rightt1Layout);
        Rightt1Layout.setHorizontalGroup(
            Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Rightt1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Location_Button1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Module_Button1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Course_Button1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Rightt1Layout.createSequentialGroup()
                        .addComponent(Start_Time3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Group1)
                        .addGap(63, 63, 63))
                    .addGroup(Rightt1Layout.createSequentialGroup()
                        .addComponent(Type_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Group_Button1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Rightt1Layout.createSequentialGroup()
                        .addGroup(Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Location1)
                            .addComponent(Course1)
                            .addComponent(Module1)
                            .addComponent(Staff_Allocation1)
                            .addGroup(Rightt1Layout.createSequentialGroup()
                                .addComponent(StaffAllocation_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Date1)
                            .addGroup(Rightt1Layout.createSequentialGroup()
                                .addGroup(Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Start_Time2)
                                    .addComponent(StartTime_Button1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Duration_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Duration1)))
                            .addComponent(DateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Rightt1Layout.setVerticalGroup(
            Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Rightt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Course1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Course_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Module1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Module_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Group1)
                    .addComponent(Start_Time3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Type_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Group_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(Location1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Location_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Date1)
                .addGap(2, 2, 2)
                .addComponent(DateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Rightt1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Duration1))
                    .addComponent(Start_Time2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Duration_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartTime_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Staff_Allocation1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Rightt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffAllocation_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modify))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        Dropdowns.addTab("Modify", Rightt1);

        javax.swing.GroupLayout Manage_TimetablesLayout = new javax.swing.GroupLayout(Manage_Timetables);
        Manage_Timetables.setLayout(Manage_TimetablesLayout);
        Manage_TimetablesLayout.setHorizontalGroup(
            Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_TimetablesLayout.createSequentialGroup()
                .addComponent(Table_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dropdowns, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Manage_TimetablesLayout.setVerticalGroup(
            Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .addGroup(Manage_TimetablesLayout.createSequentialGroup()
                .addComponent(Dropdowns, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Admin.addTab("Manage Timetables", Manage_Timetables);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        Event e = mttm.getEvent(eventsTable.getSelectedRow());

        mttm.removeEvent(e);
        eventsTable.updateUI();
    }//GEN-LAST:event_RemoveActionPerformed

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        
        String id = requestTable.getValueAt(requestTable.getSelectedRow(), 0).toString();
        respondToRequest(id, Course_Button2.getSelectedItem().toString(), true);
    }//GEN-LAST:event_Add1ActionPerformed

    private void DenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenyActionPerformed
        respondToRequest(requestTable.getValueAt(requestTable.getSelectedRow(), 0).toString(), Course_Button2.getSelectedItem().toString(), false);
    }//GEN-LAST:event_DenyActionPerformed

    private void StartTime_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTime_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartTime_ButtonActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        Boolean repeat = false;

        if ((Course_Button.getSelectedIndex() > -1) && (Module_Button.getSelectedIndex() > -1) && (Location_Button.getSelectedIndex() > -1)) {
            if (DateChooser.getDate().toString().contains("Sat") || DateChooser.getDate().toString().contains("Sun")) {
                JOptionPane.showMessageDialog(null, "No classes on saturday or sunday");
                repeat = true;
            } else {

                if (repeat.equals(false)) {
                    Event e = createEvent();

                    if (Type_button.getSelectedItem().toString().equals("Lecture")) {
                        e.setGroup("");
                        mttm.addEvent(e);
                        eventsTable.updateUI();
                    } else {
                        mttm.addEvent(e);
                        eventsTable.updateUI();
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Dropdowns can not be left empty");
        }
    }//GEN-LAST:event_AddActionPerformed

    private void Group_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Group_ButtonActionPerformed
        List<String> RoomsList = getRooms(Course_Button.getSelectedItem().toString(), Group_Button.getSelectedItem().toString(), Type_button.getSelectedItem().toString());
        String[] Rooms = new String[RoomsList.size()];
        for (int i = 0; i < RoomsList.size(); i++) {
            Rooms[i] = RoomsList.get(i);
        }
        this.Location_Button.setModel(new javax.swing.DefaultComboBoxModel<String>(Rooms));
    }//GEN-LAST:event_Group_ButtonActionPerformed

    private void Course_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_ButtonActionPerformed
        try {
            mttm = new ManageTimetablesTableModel(getAllEvents(Course_Button.getSelectedItem().toString()));
        } catch (Exception e) {
            e.getMessage();
        }
        eventsTable.setModel(mttm);

// TODO add your handling code here:
        List<String> moduleNamesList = getModules(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));

        String[] moduleNames = new String[moduleNamesList.size()];
        for (int i = 0; i < moduleNamesList.size(); i++) {
            moduleNames[i] = moduleNamesList.get(i).split("-")[1];
        }

        this.Module_Button.setModel(new javax.swing.DefaultComboBoxModel<String>(moduleNames));

        List<String> staffNamesList = getFacultyMembers(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));

        String[] staffNames = new String[staffNamesList.size()];
        for (int i = 0; i < staffNamesList.size(); i++) {
            staffNames[i] = staffNamesList.get(i).split("-")[1];
        }

        this.StaffAllocation_Button.setModel(new javax.swing.DefaultComboBoxModel<String>(staffNames));

        //add events to table from getAllEvents

    }//GEN-LAST:event_Course_ButtonActionPerformed

    private void Module_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Module_ButtonActionPerformed
        // TODO add your handling code here:
        List<String> moduleNamesList = getModules(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));
        String modname = this.Module_Button.getSelectedItem().toString();
        int foundIndex = 0;
        for (int i = 0; i < moduleNamesList.size(); i++) {
            if (modname.equals(moduleNamesList.get(i).split("-")[1])) {
                foundIndex = i;
                break;
            }
        }

        List<String> GroupsList = getGroups(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()), moduleNamesList.get(foundIndex).split("-")[0]);
        String[] Groups = new String[GroupsList.size()];
        for (int i = 0; i < GroupsList.size(); i++) {
            Groups[i] = GroupsList.get(i).split("-")[1];
        }

        this.Group_Button.setModel(new javax.swing.DefaultComboBoxModel<String>(Groups));
    }//GEN-LAST:event_Module_ButtonActionPerformed

    private void StartTime_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTime_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartTime_Button1ActionPerformed

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed

        Boolean repeat = false;
        if ((Course_Button1.getSelectedIndex() > -1) && (Module_Button1.getSelectedIndex() > -1) && (Location_Button1.getSelectedIndex() > -1)) {

            if (DateChooser1.getDate().toString().contains("Sat") || DateChooser1.getDate().toString().contains("Sun")) {
                JOptionPane.showMessageDialog(null, "No classes on saturday or sunday");
                repeat = true;
            } else if (eventsTable.getSelectedRow() > -1) {
                Event a = mttm.getEvent(eventsTable.getSelectedRow());
                mttm.removeEvent(a);
                Event b = modifyEvent();
                repeat = mttm.checkEvent(b);

                if (repeat.equals(false)) {
                    if (Type_button1.getSelectedItem().toString().equals("Lecture")) {

                        b.setGroup("");
                        mttm.addEvent(b);
                        eventsTable.updateUI();
                    } else {
                        mttm.addEvent(b);
                        eventsTable.updateUI();
                    }
                } else {
                    mttm.addEvent(a);
                    eventsTable.updateUI();
                }
            } else {
                JOptionPane.showMessageDialog(this, "No selected row");
                repeat = true;
            }

        } else {
            JOptionPane.showMessageDialog(this, "Dropdowns can not be left empty");

        }
    }//GEN-LAST:event_ModifyActionPerformed

    private void Group_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Group_Button1ActionPerformed
        List<String> MRoomsList = getRooms(Course_Button1.getSelectedItem().toString(), Group_Button1.getSelectedItem().toString(), Type_button1.getSelectedItem().toString());
        String[] MRooms = new String[MRoomsList.size()];
        for (int i = 0; i < MRoomsList.size(); i++) {
            MRooms[i] = MRoomsList.get(i);
        }
        this.Location_Button1.setModel(new javax.swing.DefaultComboBoxModel<String>(MRooms));
    }//GEN-LAST:event_Group_Button1ActionPerformed

    private void Course_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_Button1ActionPerformed
        // TODO add your handling code here:
        List<String> MmoduleNamesList = getModules(this.Course_Button1.getItemAt(this.Course_Button1.getSelectedIndex()));

        String[] MmoduleNames = new String[MmoduleNamesList.size()];
        for (int i = 0; i < MmoduleNamesList.size(); i++) {
            MmoduleNames[i] = MmoduleNamesList.get(i).split("-")[1];
        }

        this.Module_Button1.setModel(new javax.swing.DefaultComboBoxModel<String>(MmoduleNames));

        List<String> MstaffNamesList = getFacultyMembers(this.Course_Button1.getItemAt(this.Course_Button1.getSelectedIndex()));

        String[] MstaffNames = new String[MstaffNamesList.size()];
        for (int i = 0; i < MstaffNamesList.size(); i++) {
            MstaffNames[i] = MstaffNamesList.get(i).split("-")[1];
        }

        this.StaffAllocation_Button1.setModel(new javax.swing.DefaultComboBoxModel<String>(MstaffNames));
    }//GEN-LAST:event_Course_Button1ActionPerformed

    private void Module_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Module_Button1ActionPerformed
        // TODO add your handling code here:
        List<String> moduleNamesList = getModules(this.Course_Button1.getItemAt(this.Course_Button1.getSelectedIndex()));
        String modname = this.Module_Button1.getSelectedItem().toString();
        int foundIndex = 0;
        for (int i = 0; i < moduleNamesList.size(); i++) {
            if (modname.equals(moduleNamesList.get(i).split("-")[1])) {
                foundIndex = i;
                break;
            }
        }

        List<String> GroupsList = getGroups(this.Course_Button1.getItemAt(this.Course_Button1.getSelectedIndex()), moduleNamesList.get(foundIndex).split("-")[0]);
        String[] Groups = new String[GroupsList.size()];
        for (int i = 0; i < GroupsList.size(); i++) {
            Groups[i] = GroupsList.get(i).split("-")[1];
        }

        this.Group_Button1.setModel(new javax.swing.DefaultComboBoxModel<String>(Groups));
    }//GEN-LAST:event_Module_Button1ActionPerformed

    private void Course_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_Button2ActionPerformed
        try {
            artm = new adminRequestTableModel(getRequests(Course_Button2.getSelectedItem().toString()));
            requestTable.setModel(artm);
            requestTable.updateUI();
        } catch (Exception e) {
            e.getMessage();
        }

    }//GEN-LAST:event_Course_Button2ActionPerformed

    private void Type_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Type_buttonActionPerformed

    private void requestTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestTableMouseReleased

        Display.setText(artm.req(requestTable.getSelectedRow()));
    }//GEN-LAST:event_requestTableMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Admin().setVisible(true);

            }
        });
    }

    private Event createEvent() {
        Event Package = new Event();
        Package.setCourseId(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));
        Package.setModuleName(this.Module_Button.getItemAt(this.Module_Button.getSelectedIndex()));
        Package.setGroup(this.Group_Button.getItemAt(this.Group_Button.getSelectedIndex()));
        Package.setRoomId(this.Location_Button.getItemAt(this.Location_Button.getSelectedIndex()));
        Package.setType(this.Type_button.getItemAt(this.Type_button.getSelectedIndex()));

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String Date = sdf.format(DateChooser.getDate());
        Package.setDate(Date);
        String StartTime = StartTime_Button.getSelectedItem().toString();
        String Duration = Duration_Button.getSelectedItem().toString();
        int TimeSlot1 = Integer.parseInt(StartTime) + Integer.parseInt(Duration);

        Package.setTimeStamp(StartTime_Button.getSelectedItem() + ":00 - " + TimeSlot1 + ":00");
        Package.setTutor(this.StaffAllocation_Button.getSelectedItem().toString());
        //find module id
        List<String> moduleNamesList = getModules(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));
        String modname = this.Module_Button.getItemAt(this.Module_Button.getSelectedIndex());
        int foundIndex = 0;
        for (int x = 0; x < moduleNamesList.size(); x++) {
            if (modname.equals(moduleNamesList.get(x).split("-")[1])) {
                Package.setModuleId(moduleNamesList.get(x).split("-")[0]);
                foundIndex = x;
            }
        }

        List<String> staffNamesList = getFacultyMembers(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));

        for (int y = 0; y < staffNamesList.size(); y++) {
            if (Package.getTutor().equals(staffNamesList.get(y).split("-")[1])) {
                Package.setTutor(staffNamesList.get(y).split("-")[0]);
                break;
            }
        }
        String info = getFacultyMembersInfo(Package.getCourseId(), Package.getTutor());
        Package.setTutorEmail(info.split("-")[0]);
        Package.setTutorOffice(info.split("-")[1]);

        Package.setEventId(this.Course_Button.getSelectedItem().toString() + Package.getModuleId() + this.Type_button.getSelectedItem().toString() + Package.getTimeStamp());

        return Package;
    }

    private Event modifyEvent() {
        Event Package = new Event();
        Package.setCourseId(this.Course_Button1.getItemAt(this.Course_Button1.getSelectedIndex()));
        Package.setModuleName(this.Module_Button1.getItemAt(this.Module_Button1.getSelectedIndex()));
        Package.setGroup(this.Group_Button1.getItemAt(this.Group_Button1.getSelectedIndex()));
        Package.setRoomId(this.Location_Button1.getItemAt(this.Location_Button1.getSelectedIndex()));
        Package.setType(this.Type_button1.getItemAt(this.Type_button1.getSelectedIndex()));

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String Date = sdf.format(DateChooser1.getDate());
        Package.setDate(Date);
        String StartTime = StartTime_Button1.getSelectedItem().toString();
        String Duration = Duration_Button1.getSelectedItem().toString();
        int TimeSlot1 = Integer.parseInt(StartTime) + Integer.parseInt(Duration);

        Package.setTimeStamp(StartTime_Button1.getSelectedItem() + ":00 - " + TimeSlot1 + ":00");
        Package.setTutor(this.StaffAllocation_Button1.getSelectedItem().toString());
        //find module id
        List<String> moduleNamesList = getModules(this.Course_Button1.getItemAt(this.Course_Button1.getSelectedIndex()));
        String modname = this.Module_Button1.getItemAt(this.Module_Button1.getSelectedIndex());
        int foundIndex = 0;
        for (int x = 0; x < moduleNamesList.size(); x++) {
            if (modname.equals(moduleNamesList.get(x).split("-")[1])) {
                Package.setModuleId(moduleNamesList.get(x).split("-")[0]);
                foundIndex = x;
            }
        }

        List<String> staffNamesList = getFacultyMembers(this.Course_Button1.getItemAt(this.Course_Button1.getSelectedIndex()));

        for (int y = 0; y < staffNamesList.size(); y++) {
            if (Package.getTutor().equals(staffNamesList.get(y).split("-")[1])) {
                Package.setTutor(staffNamesList.get(y).split("-")[0]);
                break;
            }
        }
        String info = getFacultyMembersInfo(Package.getCourseId(), Package.getTutor());
        Package.setTutorEmail(info.split("-")[0]);
        Package.setTutorOffice(info.split("-")[1]);

        Package.setEventId(this.Course_Button1.getSelectedItem().toString() + Package.getModuleId() + this.Type_button1.getSelectedItem().toString() + Package.getTimeStamp());

        return Package;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Add1;
    private javax.swing.JTabbedPane Admin;
    private javax.swing.JLabel Course;
    private javax.swing.JLabel Course1;
    private javax.swing.JComboBox<String> Course_Button;
    private javax.swing.JComboBox<String> Course_Button1;
    private javax.swing.JComboBox<String> Course_Button2;
    private javax.swing.JLabel Course_Label_Manage_Requests;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Date1;
    private com.toedter.calendar.JDateChooser DateChooser;
    private com.toedter.calendar.JDateChooser DateChooser1;
    private javax.swing.JButton Deny;
    private javax.swing.JTextArea Display;
    private javax.swing.JTabbedPane Dropdowns;
    private javax.swing.JLabel Duration;
    private javax.swing.JLabel Duration1;
    private javax.swing.JComboBox<String> Duration_Button;
    private javax.swing.JComboBox<String> Duration_Button1;
    private javax.swing.JLabel Group;
    private javax.swing.JLabel Group1;
    private javax.swing.JComboBox<String> Group_Button;
    private javax.swing.JComboBox<String> Group_Button1;
    private javax.swing.JPanel LeftR;
    private javax.swing.JLabel Location;
    private javax.swing.JLabel Location1;
    private javax.swing.JComboBox<String> Location_Button;
    private javax.swing.JComboBox<String> Location_Button1;
    private javax.swing.JPanel Manage_Requests;
    private javax.swing.JPanel Manage_Timetables;
    private javax.swing.JButton Modify;
    private javax.swing.JLabel Module;
    private javax.swing.JLabel Module1;
    private javax.swing.JComboBox<String> Module_Button;
    private javax.swing.JComboBox<String> Module_Button1;
    private javax.swing.JButton Remove;
    private javax.swing.JLabel Request_Description_label;
    private javax.swing.JPanel RightR;
    private javax.swing.JPanel Rightt;
    private javax.swing.JPanel Rightt1;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JSeparator Separator;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JComboBox<String> StaffAllocation_Button;
    private javax.swing.JComboBox<String> StaffAllocation_Button1;
    private javax.swing.JLabel Staff_Allocation;
    private javax.swing.JLabel Staff_Allocation1;
    private javax.swing.JComboBox<String> StartTime_Button;
    private javax.swing.JComboBox<String> StartTime_Button1;
    private javax.swing.JLabel Start_Time;
    private javax.swing.JLabel Start_Time1;
    private javax.swing.JLabel Start_Time2;
    private javax.swing.JLabel Start_Time3;
    private javax.swing.JPanel Table_Panel;
    private javax.swing.JComboBox<String> Type_button;
    private javax.swing.JComboBox<String> Type_button1;
    private static javax.swing.JTable eventsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> getCourseIds() {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getCourseIds();
    }

    private static java.util.List<java.lang.String> getModules(java.lang.String arg0) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getModules(arg0);
    }

    private static java.util.List<java.lang.String> getFacultyMembers(java.lang.String arg0) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getFacultyMembers(arg0);
    }

    private static java.util.List<java.lang.String> getGroups(java.lang.String arg0, java.lang.String arg1) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getGroups(arg0, arg1);
    }

    private static java.util.List<org.netbeans.xml.schema.timetable.Event> getAllEvents(java.lang.String arg0) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getAllEvents(arg0);
    }

    private static java.util.List<org.netbeans.xml.schema.timetable.Request> getRequests(java.lang.String arg0) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getRequests(arg0);
    }

    private static String getFacultyMembersInfo(java.lang.String arg0, java.lang.String arg1) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getFacultyMembersInfo(arg0, arg1);
    }

    private static java.util.List<java.lang.String> getRooms(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getRooms(arg0, arg1, arg2);
    }

    private static void respondToRequest(java.lang.String id, java.lang.String arg1, java.lang.Boolean arg2) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        port.respondToRequest(id, arg1, arg2);
    }

}
