/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablingclient;

import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.netbeans.xml.schema.timetable.Event;
import org.netbeans.xml.schema.timetable.Request;
import org.netbeans.xml.schema.timetable.Staff;
import static timetablingclient.Admin.artm;
import static timetablingclient.Admin.mttm;

/**
 *
 * @author Tanaka
 */
public class Faculty extends javax.swing.JFrame {

    static facultyRequestTableModel frtm;
    static ManageTimetablesTableModel ttm;

    Staff staff = new Staff();

    /**
     * Creates new form Admin_manage_requests
     */
    public Faculty(String ID) {
        this.staff.setStaffID(ID);
        this.staff.setCourse(getStaffLoginInfo(ID).split(":")[1]);
        this.staff.setSeed(getStaffLoginInfo(ID).split(":")[2]);

        initComponents();
        frtm = new facultyRequestTableModel(getSentRequests(this.staff.getStaffID(), this.staff.getCourse()));
        requestTable.setModel(frtm);
        requestTable.updateUI();
        previous();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Admin = new javax.swing.JTabbedPane();
        Manage_Requests = new javax.swing.JPanel();
        LeftR = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextBox_New_Request = new javax.swing.JEditorPane();
        Comment_Label_New_Requests = new javax.swing.JLabel();
        Submit_Button_New_Request = new javax.swing.JButton();
        Cancel_Button_New_Request = new javax.swing.JButton();
        Group_Label_New_Request = new javax.swing.JLabel();
        Event_Type_ComboBox = new javax.swing.JComboBox<>();
        Event_Type = new javax.swing.JLabel();
        Module = new javax.swing.JLabel();
        List<String> courseIdsList = getCourseIds();

        String[] courseIds = new String[courseIdsList.size()];

        for (int i = 0; i < courseIdsList.size(); i++){
            courseIds[i] = courseIdsList.get(i);
        }
        Course_Button = new javax.swing.JComboBox<>();
        Module_Button = new javax.swing.JComboBox<>();
        Group_Button = new javax.swing.JComboBox<>();
        Course = new javax.swing.JLabel();
        Separator1 = new javax.swing.JSeparator();
        Manage_Timetables = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Timetable = new javax.swing.JTable();
        Next = new javax.swing.JButton();
        Previous = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(940, 380));

        LeftR.setPreferredSize(new java.awt.Dimension(650, 450));

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(requestTable);

        javax.swing.GroupLayout LeftRLayout = new javax.swing.GroupLayout(LeftR);
        LeftR.setLayout(LeftRLayout);
        LeftRLayout.setHorizontalGroup(
            LeftRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        LeftRLayout.setVerticalGroup(
            LeftRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TextBox_New_Request.setPreferredSize(new java.awt.Dimension(100, 100));
        jScrollPane3.setViewportView(TextBox_New_Request);

        Comment_Label_New_Requests.setText("Comments:");

        Submit_Button_New_Request.setText("Submit");
        Submit_Button_New_Request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_Button_New_RequestActionPerformed(evt);
            }
        });

        Cancel_Button_New_Request.setText("Clear");
        Cancel_Button_New_Request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_Button_New_RequestActionPerformed(evt);
            }
        });

        Group_Label_New_Request.setText("Group");

        Event_Type_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture", "Seminar", "Laboratory" }));

        Event_Type.setText("Event Type:");

        Module.setText("Module:");

        Course_Button.setModel(new javax.swing.DefaultComboBoxModel<String>(courseIds));
        Course_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_ButtonActionPerformed(evt);
            }
        });

        Module_Button.setModel(new javax.swing.DefaultComboBoxModel<String>());
        Module_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Module_ButtonActionPerformed(evt);
            }
        });

        Group_Button.setModel(new javax.swing.DefaultComboBoxModel<String>());
        Group_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Group_ButtonActionPerformed(evt);
            }
        });

        Course.setText("Course");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Event_Type_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(106, 106, 106)
                                .addComponent(Group_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Course_Button, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(106, 106, 106))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Event_Type)
                                            .addComponent(Course))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Module)
                                    .addComponent(Module_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Group_Label_New_Request))))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Comment_Label_New_Requests)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Cancel_Button_New_Request)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Submit_Button_New_Request))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Course)
                    .addComponent(Module))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Course_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Module_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Group_Label_New_Request)
                    .addComponent(Event_Type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Event_Type_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Group_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comment_Label_New_Requests)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel_Button_New_Request)
                    .addComponent(Submit_Button_New_Request))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Separator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout Manage_RequestsLayout = new javax.swing.GroupLayout(Manage_Requests);
        Manage_Requests.setLayout(Manage_RequestsLayout);
        Manage_RequestsLayout.setHorizontalGroup(
            Manage_RequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_RequestsLayout.createSequentialGroup()
                .addComponent(LeftR, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Manage_RequestsLayout.setVerticalGroup(
            Manage_RequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_RequestsLayout.createSequentialGroup()
                .addGroup(Manage_RequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Separator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(LeftR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        Admin.addTab("Manage Requests", Manage_Requests);

        Timetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "From", "To", "Room", "Lecturer", "Type", "Module Code", "Module Name", "Group"
            }
        ));
        jScrollPane1.setViewportView(Timetable);

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Previous.setText("Previous");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Manage_TimetablesLayout = new javax.swing.GroupLayout(Manage_Timetables);
        Manage_Timetables.setLayout(Manage_TimetablesLayout);
        Manage_TimetablesLayout.setHorizontalGroup(
            Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Manage_TimetablesLayout.createSequentialGroup()
                .addGroup(Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Manage_TimetablesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Previous)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 863, Short.MAX_VALUE)
                        .addComponent(Next)))
                .addGap(265, 265, 265))
        );
        Manage_TimetablesLayout.setVerticalGroup(
            Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_TimetablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next)
                    .addComponent(Previous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
        );

        Admin.addTab("View Timetable", Manage_Timetables);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Course_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_ButtonActionPerformed
        // TODO add your handling code here:
        List<String> moduleNamesList = getModules(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));

        String[] moduleNames = new String[moduleNamesList.size()];
        for (int i = 0; i < moduleNamesList.size(); i++) {
            moduleNames[i] = moduleNamesList.get(i).split("-")[1];
        }

        this.Module_Button.setModel(new javax.swing.DefaultComboBoxModel<String>(moduleNames));
    }//GEN-LAST:event_Course_ButtonActionPerformed

    private void Module_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Module_ButtonActionPerformed
        // TODO add your handling code here:
        List<String> moduleNamesList = getModules(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));
        String modname = this.Module_Button.getSelectedItem().toString();
        int foundIndex = 0;
        for (int i = 0; i < moduleNamesList.size(); i++) {
            if (modname.equals(moduleNamesList.get(i).split("-")[1])) {
                foundIndex = i;
                break;
            }
        }

        List<String> GroupsList = getGroups(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()), moduleNamesList.get(foundIndex).split("-")[0]);
        String[] Groups = new String[GroupsList.size()];
        for (int i = 0; i < GroupsList.size(); i++) {
            Groups[i] = GroupsList.get(i).split("-")[1];
        }

        this.Group_Button.setModel(new javax.swing.DefaultComboBoxModel<String>(Groups));
    }//GEN-LAST:event_Module_ButtonActionPerformed

    private void Group_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Group_ButtonActionPerformed

    }//GEN-LAST:event_Group_ButtonActionPerformed

    private void Cancel_Button_New_RequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_Button_New_RequestActionPerformed
        TextBox_New_Request.setText("");
    }//GEN-LAST:event_Cancel_Button_New_RequestActionPerformed

    private void Submit_Button_New_RequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_Button_New_RequestActionPerformed
        try {
            if ((Course_Button.getSelectedIndex() > -1) && (Module_Button.getSelectedIndex() > -1) && (Group_Button.getSelectedIndex() > -1) && (!TextBox_New_Request.getText().isEmpty())) {
                Request e = req();
                sendRequest(e, Course_Button.getSelectedItem().toString());
                System.out.println(TextBox_New_Request.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Dropdowns and comment box cannot be left empty");
            }
        } catch (Exception e) {
            e.getMessage();
        }

    }//GEN-LAST:event_Submit_Button_New_RequestActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        next();
        Previous.setVisible(true);
    }//GEN-LAST:event_NextActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        previous();
        Next.setVisible(true);
    }//GEN-LAST:event_PreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Faculty().setVisible(true);
            }
        });
    }

    public Date getFirstDayOfWeekDate(int firstDay) {

        Calendar c = new GregorianCalendar();

        while (c.get(Calendar.DAY_OF_WEEK) != firstDay-1) {
            c.add(Calendar.DAY_OF_MONTH, -1);
        }
        c.add(Calendar.DAY_OF_WEEK, -1);
        return c.getTime();
    }

    public Date getLastDayOfWeekDate(int lastDay) {

        Calendar c = new GregorianCalendar();

        while (c.get(Calendar.DAY_OF_WEEK) != lastDay) {
            c.add(Calendar.DAY_OF_MONTH, -1);
        }
        c.add(Calendar.DAY_OF_WEEK, +5);
        return c.getTime();
    }

    public Date getFirstDayOfNextWeekDate(int firstDay) {

        Calendar c = new GregorianCalendar();

        while (c.get(Calendar.DAY_OF_WEEK) != firstDay -1) {
            c.add(Calendar.DAY_OF_MONTH, +1);
        }

        return c.getTime();
    }

    public Date getLastDayNextOfWeekDate(int lastDay) {

        Calendar c = new GregorianCalendar();

        while (c.get(Calendar.DAY_OF_WEEK) != lastDay) {
            c.add(Calendar.DAY_OF_MONTH, +1);
        }
        c.add(Calendar.DAY_OF_WEEK, +5);
        return c.getTime();
    }

    public void previous() {
        Calendar rightNow = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String sw1 = sdf.format(getFirstDayOfWeekDate(rightNow.getFirstDayOfWeek()));
        String ew1 = sdf.format(getLastDayOfWeekDate(rightNow.getFirstDayOfWeek()));
        try {
            //getEvents(String id, String dateFrom , String dateTo , String courseId)
            List<Event> events = getMyEvents(Login.user, sw1, ew1, "cmpsci");
            ttm = new ManageTimetablesTableModel(getMyEvents(Login.user, sw1, ew1, "cmpsci"));
        } catch (Exception e) {
            e.getMessage();
        }
        Timetable.setModel(ttm);
        Previous.setVisible(false);
    }

    public void next() {
        Calendar rightNow = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String sw2 = sdf.format(getFirstDayOfNextWeekDate(rightNow.getFirstDayOfWeek()));
        String ew2 = sdf.format(getLastDayNextOfWeekDate(rightNow.getFirstDayOfWeek()));
        try {
            //getEvents(String id, String dateFrom , String dateTo , String courseId)
            List<Event> events = getMyEvents(Login.user, sw2, ew2, "cmpsci");
            ttm = new ManageTimetablesTableModel(getMyEvents(Login.user, sw2, ew2, "cmpsci"));
        } catch (Exception e) {
            e.getMessage();
        }
        Timetable.setModel(ttm);
        Next.setVisible(false);
    }

    private Request req() {
        Request Package = new Request();
        Package.setStaffID(Login.user);
        Package.setCourseID(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));
        Package.setModuleID(this.Module_Button.getItemAt(this.Module_Button.getSelectedIndex()));
        Package.setGroupID(this.Group_Button.getItemAt(this.Group_Button.getSelectedIndex()));
        Package.setRequest(TextBox_New_Request.getText());
        int ID = requestTable.getRowCount();

        List<String> moduleNamesList = getModules(this.Course_Button.getItemAt(this.Course_Button.getSelectedIndex()));
        String modname = this.Module_Button.getItemAt(this.Module_Button.getSelectedIndex());
        int foundIndex = 0;
        String modID = new String();
        for (int x = 0; x < moduleNamesList.size(); x++) {
            if (modname.equals(moduleNamesList.get(x).split("-")[1])) {
                    modID = moduleNamesList.get(x).split("-")[0];
                foundIndex = x;
            }
        }

        Package.setRequestID(Login.user +  modID + Integer.toString(ID));
        Package.setStatus("Pending");
        return Package;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Admin;
    private javax.swing.JButton Cancel_Button_New_Request;
    private javax.swing.JLabel Comment_Label_New_Requests;
    private javax.swing.JLabel Course;
    private javax.swing.JComboBox<String> Course_Button;
    private javax.swing.JLabel Event_Type;
    private javax.swing.JComboBox<String> Event_Type_ComboBox;
    private javax.swing.JComboBox<String> Group_Button;
    private javax.swing.JLabel Group_Label_New_Request;
    private javax.swing.JPanel LeftR;
    private javax.swing.JPanel Manage_Requests;
    private javax.swing.JPanel Manage_Timetables;
    private javax.swing.JLabel Module;
    private javax.swing.JComboBox<String> Module_Button;
    private javax.swing.JButton Next;
    private javax.swing.JButton Previous;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JButton Submit_Button_New_Request;
    private javax.swing.JEditorPane TextBox_New_Request;
    private javax.swing.JTable Timetable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> getModules(java.lang.String arg0) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getModules(arg0);
    }

    private static java.util.List<java.lang.String> getFacultyMembers(java.lang.String arg0) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getFacultyMembers(arg0);
    }

    private static java.util.List<java.lang.String> getGroups(java.lang.String arg0, java.lang.String arg1) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getGroups(arg0, arg1);
    }

    private static java.util.List<java.lang.String> getCourseIds() {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getCourseIds();
    }

    private static java.util.List<org.netbeans.xml.schema.timetable.Request> getRequests(java.lang.String arg0) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getRequests(arg0);
    }

    private static java.util.List<org.netbeans.xml.schema.timetable.Event> getMyEvents(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getMyEvents(arg0, arg1, arg2, arg3);
    }

    private static boolean sendRequest(org.netbeans.xml.schema.timetable.Request newRequest, java.lang.String arg1) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.sendRequest(newRequest, arg1);
    }

    private static String getStaffLoginInfo(java.lang.String arg0) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getStaffLoginInfo(arg0);
    }

    private static java.util.List<org.netbeans.xml.schema.timetable.Request> getSentRequests(java.lang.String id, java.lang.String arg1) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getSentRequests(id, arg1);
    }

}
