/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablingclient;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Scanner;
import org.netbeans.xml.schema.timetable.Student;
import timetablewebservices.GetStudentResponse;

/**
 *
 * @author n0719344
 */
public class StudentTT extends javax.swing.JFrame {
    
    
    static ManageTimetablesTableModel thisWeek;
    static ManageTimetablesTableModel nextWeek;
    static ManageTimetablesTableModel init;
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    
    Student student = new Student();
    
    /**
     * Creates new form Student
     */
    public StudentTT(String ID) {
        
        initComponents();
        this.student.setStudentID(ID);
        
        this.student.setCourseId(getStudent(ID).split(":")[1]);
        this.student.setSeed(getStudent(ID).split(":")[2]);
        
        
        Calendar rightNow = Calendar.getInstance();
        String sw1 = sdf.format(getFirstDayOfWeekDate(rightNow.getFirstDayOfWeek()));
        String ew1 = sdf.format(getLastDayOfWeekDate(rightNow.getFirstDayOfWeek()));
        
        init = new ManageTimetablesTableModel(getMyEvents(this.student.getStudentID(),sw1,ew1,this.student.getCourseId()));
        timeTable.setModel(init);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manage_Timetables = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        timeTable = new javax.swing.JTable();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(940, 380));

        timeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "From", "To", "Room", "Lecturer", "Type", "Module Code", "Module Name", "Group"
            }
        ));
        jScrollPane1.setViewportView(timeTable);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Manage_TimetablesLayout = new javax.swing.GroupLayout(Manage_Timetables);
        Manage_Timetables.setLayout(Manage_TimetablesLayout);
        Manage_TimetablesLayout.setHorizontalGroup(
            Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_TimetablesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextButton)
                    .addComponent(previousButton))
                .addGap(0, 86, Short.MAX_VALUE))
        );
        Manage_TimetablesLayout.setVerticalGroup(
            Manage_TimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(Manage_TimetablesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(nextButton)
                .addGap(18, 18, 18)
                .addComponent(previousButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Manage_Timetables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Manage_Timetables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        Calendar rightNow = Calendar.getInstance();
        
        
        String sw1 = sdf.format(getFirstDayOfNextWeekDate(rightNow.getFirstDayOfWeek()));
        String ew1 = sdf.format(getLastDayNextOfWeekDate(rightNow.getFirstDayOfWeek()));
        
        nextWeek = new ManageTimetablesTableModel(getMyEvents(this.student.getStudentID(),sw1,ew1,this.student.getCourseId()));
        timeTable.setModel(nextWeek);
        timeTable.updateUI();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        Calendar rightNow = Calendar.getInstance();
        String sw1 = sdf.format(getFirstDayOfWeekDate(rightNow.getFirstDayOfWeek()));
        String ew1 = sdf.format(getLastDayOfWeekDate(rightNow.getFirstDayOfWeek()));
        
        thisWeek = new ManageTimetablesTableModel(getMyEvents(this.student.getStudentID(),sw1,ew1,this.student.getCourseId()));
        timeTable.setModel(thisWeek);
        timeTable.updateUI();
    }//GEN-LAST:event_previousButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new StudentTT().setVisible(true);
            }
        });
    }
    
    
    public Date getFirstDayOfWeekDate(int firstDay) {

        Calendar c = new GregorianCalendar();

        while (c.get(Calendar.DAY_OF_WEEK) != firstDay-1) {
            c.add(Calendar.DAY_OF_WEEK, -1);
        }
        return c.getTime();
    }

    public Date getLastDayOfWeekDate(int lastDay) {

        Calendar c = new GregorianCalendar();

        while (c.get(Calendar.DAY_OF_WEEK) != lastDay) {
            c.add(Calendar.DAY_OF_MONTH, -1);
        }
        c.add(Calendar.DAY_OF_WEEK, +5);
        return c.getTime();
    }

    public Date getFirstDayOfNextWeekDate(int firstDay) {

        Calendar c = new GregorianCalendar();

        while (c.get(Calendar.DAY_OF_WEEK) != firstDay-1) {
            c.add(Calendar.DAY_OF_MONTH, +1);
        }
        return c.getTime();
    }

    public Date getLastDayNextOfWeekDate(int lastDay) {

        Calendar c = new GregorianCalendar();

        while (c.get(Calendar.DAY_OF_WEEK) != lastDay) {
            c.add(Calendar.DAY_OF_MONTH, +1);
        }
        c.add(Calendar.DAY_OF_WEEK, +5);
        return c.getTime();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Manage_Timetables;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JTable timeTable;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<org.netbeans.xml.schema.timetable.Event> getMyEvents(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getMyEvents(arg0, arg1, arg2, arg3);
    }

    private static String getStudent(java.lang.String arg0) {
        timetablewebservices.Timetabling_Service service = new timetablewebservices.Timetabling_Service();
        timetablewebservices.Timetabling port = service.getTimetablingPort();
        return port.getStudent(arg0);
    }






    

   

}
